---
# internal.vmware.vcsa : tasks/main.yaml

- name: "VCSA | Dispatch"
  module_defaults:
    group/community.vmware.vmware:
      hostname: "{{ _vcenter_hostname }}"
      username: "{{ vmware_username }}"
      password: "{{ vmware_password }}"
      validate_certs: "{{ vmware_validate_certs | default(false) | bool }}"
    vmware.vmware.appliance_info:
      hostname: "{{ _vcenter_hostname }}"
      username: "{{ vmware_username }}"
      password: "{{ vmware_password }}"
      validate_certs: "{{ vmware_validate_certs | default(false) | bool }}"
    vmware.vmware.vcsa_backup_schedule_info:
      hostname: "{{ _vcenter_hostname }}"
      username: "{{ vmware_username }}"
      password: "{{ vmware_password }}"
      validate_certs: "{{ vmware_validate_certs | default(false) | bool }}"
    vmware.vmware.cluster_info:
      hostname: "{{ _vcenter_hostname }}"
      username: "{{ vmware_username }}"
      password: "{{ vmware_password }}"
      validate_certs: "{{ vmware_validate_certs | default(false) | bool }}"
    internal.vmware.vmware_triggered_alarms_info:
      hostname: "{{ _vcenter_hostname }}"
      username: "{{ vmware_username }}"
      password: "{{ vmware_password }}"
      validate_certs: "{{ vmware_validate_certs | default(false) | bool }}"
    internal.core.stig:
      _stig_module_defaults:
        hostname: "{{ _vcenter_hostname }}"
        username: "{{ vmware_username }}"
        password: "{{ vmware_password }}"
        validate_certs: "{{ vmware_validate_certs | default(false) | bool }}"
  block:
    - name: "VCSA | Include dispatcher"
      ansible.builtin.include_role:
        name: internal.core.dispatch
      vars:
        _ncs_role_label: VCSA
        _ncs_task_root: "{{ role_path }}/tasks"
        _ncs_default_action: audit
        _ncs_action_routes:
          - collect
        _ncs_validations:
          - _ncs_requested_action in ['collect', 'audit', 'remediate', 'verify']
          - (_ncs_requested_profile == 'none') or (_ncs_requested_profile == 'stig')
          - (_ncs_requested_operation == 'none')
          - (_ncs_requested_profile != 'stig') or (_ncs_requested_action in ['audit', 'remediate', 'verify'])
        _dispatch_map:
          collect: collect
          _default_: stig
