---
# internal.linux.ubuntu : tasks/export.yaml
- name: "Ubuntu STIG | Export | Push audit results to ncs_collector"
  ansible.builtin.set_stats:
    data:
      ncs_collect:
        name: "stig_ubuntu"
        platform_dir: "{{ _ncs_platform_dir | default('linux/ubuntu') }}"
        report_directory: "{{ ubuntu_stig_artifacts_dir | default('/srv/samba/reports') }}"
        payload:
          target_type: "{{ _ncs_stig_target_type | default('ubuntu') }}"
          full_audit: "{{ _stig_full_audit | default([]) }}"
          health: "{{ 'CRITICAL' if _stig_full_audit | default([]) | selectattr('status', 'eq', 'open') | list | length > 0 else 'OK' }}"
    per_host: true
  when: _stig_full_audit is defined
  changed_when: false
