---
galaxy_info:
  author: NCS
  description: VMware Photon OS 5.0 STIG role wrapper
  company: NCS
  license: proprietary
  min_ansible_version: "2.14"
  platforms:
    - name: GenericLinux
      versions:
        - all

dependencies: []
