---
# Site 2 vCenter overrides.
# Values here apply only to hosts in the site2_vcenters group.

# esxi_stig_syslog_host: syslog.site2.yourdomain.mil
# esxi_stig_ntp_servers:
#   - 10.2.0.53
#   - 10.2.0.54
# esxi_stig_ad_domain: site2.yourdomain.mil
