---
# internal.vmware.vcsa : handlers/main.yaml
# Consolidated service restart handlers for all VCSA STIG services.

- name: restart syslog
  ansible.builtin.service:
    name: syslog
    state: restarted

- name: restart eam
  ansible.builtin.command: vmon-cli --restart eam
  register: output
  changed_when: output.rc == 0

- name: restart lookupsvc
  ansible.builtin.command: vmon-cli --restart lookupsvc
  register: output
  changed_when: output.rc == 0

- name: restart perfcharts
  ansible.builtin.command: vmon-cli --restart perfcharts
  register: output
  changed_when: output.rc == 0

- name: restart vpostgres
  ansible.builtin.command: vmon-cli --restart vmware-vpostgres
  register: output
  changed_when: output.rc == 0

- name: reload vpostgres config
  ansible.builtin.command: /opt/vmware/vpostgres/current/bin/psql -U postgres -c "SELECT pg_reload_conf();"
  register: output
  changed_when: output.rc == 0

- name: restart rhttpproxy
  ansible.builtin.command: vmon-cli --restart rhttpproxy
  register: output
  changed_when: output.rc == 0

- name: restart sts
  ansible.builtin.command: service-control --restart vmware-stsd
  register: output
  changed_when: output.rc == 0

- name: restart vsphere-ui
  ansible.builtin.command: vmon-cli --restart vsphere-ui
  register: output
  changed_when: output.rc == 0

- name: restart vami
  ansible.builtin.service:
    name: vami-lighttp
    state: restarted
