---
# internal.vmware.vcenter : tasks/stig.yaml

- name: "vCenter STIG | Load VCSA profile vars"
  ansible.builtin.include_vars: "vcsa_{{ vcenter_stig_profile | default('v1r4') }}.yml"

- name: "vCenter STIG | Optional Photon baseline"
  ansible.builtin.include_role:
    name: internal.linux.photon
  vars:
    photon_action: "{{ 'remediate' if (vmware_stig_enable_hardening | default(false) | bool) else 'stig' }}"
    photon_stig_enable_hardening: "{{ vmware_stig_enable_hardening | default(false) | bool }}"
  when: vcenter_stig_include_photon | default(false) | bool

- name: "vCenter STIG | Execute VCSA service roles"
  ansible.builtin.include_tasks: stig_role_wrapper.yaml
  loop: "{{ vcenter_stig_roles | default(_vcenter_stig_default_role_list) }}"
  loop_control:
    loop_var: _vcsa_role
    label: "{{ _vcsa_role | regex_replace('internal\\.vmware\\.vcsa_?', '') }}"
  vars:
    _vcsa_role_map:
      # internal.vmware.vcsa_misc: "vcsa"
      internal.vmware.vcsa_eam: "eam"
      internal.vmware.vcsa_lookup: "lookup_svc"
      internal.vmware.vcsa_perfcharts: "perfcharts"
      internal.vmware.vcsa_postgresql: "postgresql"
      internal.vmware.vcsa_rhttpproxy: "rhttpproxy"
      internal.vmware.vcsa_sts: "sts"
      internal.vmware.vcsa_ui: "ui"
      internal.vmware.vcsa_vami: "vami"
    _vcenter_stig_default_role_list:
      # - internal.vmware.vcsa_misc
      - internal.vmware.vcsa_eam
      - internal.vmware.vcsa_lookup
      - internal.vmware.vcsa_perfcharts
      - internal.vmware.vcsa_postgresql
      - internal.vmware.vcsa_rhttpproxy
      - internal.vmware.vcsa_sts
      - internal.vmware.vcsa_ui
      - internal.vmware.vcsa_vami

- name: "vCenter STIG | Flag run as complete"
  ansible.builtin.set_fact:
    _stig_audit_ran: true
  changed_when: false
