---
# internal.vmware.vcsa : tasks/main.yaml

- name: "VCSA | Capture task root"
  ansible.builtin.set_fact:
    _ncs_task_root: "{{ role_path }}/tasks"
  changed_when: false

- name: "VCSA | Dispatch"
  module_defaults:
    group/community.vmware.vmware: "{{ _vmware_creds }}"
    group/vmware.vmware.vmware: "{{ _vmware_creds }}"
    internal.vmware.vmware_triggered_alarms_info: "{{ _vmware_creds }}"
    internal.core.stig:
      _stig_module_defaults: "{{ _vmware_creds }}"
  block:
    - name: "VCSA | Include dispatcher"
      ansible.builtin.include_role:
        name: internal.core.dispatch
      vars:
        _ncs_role_label: VCSA
        _ncs_default_action: audit
        _ncs_action_routes:
          - collect
        _dispatch_map:
          collect: collect
          _default_: stig
