---
namespace: internal
name: windows
version: 1.1.0
readme: README.md
authors:
  - ncs
description: Windows auditing and reporting roles.
license: ["proprietary"]
tags:
  - windows
  - security
repository: https://web.git.mil/dct/ansible-ncs
