---
# tasks/v7r4/advanced_settings.yaml

- name: "Load PowerShell rules"
  ansible.builtin.include_vars:
    file: pwsh_rules.yaml

- name: "Execute Advanced Settings PowerShell STIG Rules"
  ansible.builtin.include_tasks: v7r4/pwsh_evaluator.yaml
  loop: "{{ esxi_pwsh_rules | selectattr('file', 'equalto', 'advanced_settings.yaml') | list }}"
