---
- name: reload auditd
  ansible.builtin.command: /sbin/augenrules --load
  register: output
  changed_when: output.rc == 0
  when:
    - not ansible_is_chroot

- name: reload auditdrules
  ansible.builtin.command: /sbin/augenrules --load
  register: output
  changed_when: output.rc == 0

- name: reload auditdconf
  ansible.builtin.command: pkill -SIGHUP auditd
  notify: start auditd
  register: output
  changed_when: output.rc == 0

- name: start auditd
  ansible.builtin.systemd:
    name: auditd
    state: started

- name: restart sshd
  ansible.builtin.systemd:
    name: sshd
    state: restarted

- name: restart rsyslog
  ansible.builtin.systemd:
    name: rsyslog
    state: restarted

- name: restart syslog
  ansible.builtin.systemd:
    name: rsyslog
    state: restarted

- name: restart ntpd
  ansible.builtin.systemd:
    name: ntpd
    state: restarted

- name: restart ntp
  ansible.builtin.systemd:
    name: ntpd
    state: restarted

- name: restart chrony
  ansible.builtin.systemd:
    name: chrony
    state: restarted

- name: restart timesyncd
  ansible.builtin.systemd:
    name: systemd-timesyncd
    state: restarted

- name: restart resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    state: restarted
