---
# internal.vmware.vm : tasks/stig_v7r4/main.yaml
# Per-VM V7R4 STIG dispatcher. Included via check.yaml per VM.

- import_tasks: stig_v7r4/00_prelude.yaml

- name: "Include 10_advanced_settings.yaml"
  ansible.builtin.include_tasks: stig_v7r4/10_advanced_settings.yaml

- name: "Include 20_hardware_audit.yaml"
  ansible.builtin.include_tasks: stig_v7r4/20_hardware_audit.yaml

- name: "Include 30_vm_attributes.yaml"
  ansible.builtin.include_tasks: stig_v7r4/30_vm_attributes.yaml
