---
# tasks/v7r4/network_audit.yaml
# Network / Port Group Audit Rules (pwsh query/assert)

- name: "Execute Network PowerShell STIG Rules"
  ansible.builtin.include_tasks: v7r4/pwsh_evaluator.yaml
  loop: "{{ esxi_pwsh_rules | selectattr('file', 'equalto', 'network_audit.yaml') | list }}"
