---
# internal.vmware.vm : tasks/main.yaml

- name: "VM | Dispatch"
  module_defaults:
    group/community.vmware.vmware:
      hostname: "{{ _vcenter_hostname }}"
      username: "{{ vmware_username }}"
      password: "{{ vmware_password }}"
      validate_certs: "{{ vmware_validate_certs | default(false) | bool }}"
    internal.core.stig:
      _stig_module_defaults:
        hostname: "{{ _vcenter_hostname }}"
        username: "{{ vmware_username }}"
        password: "{{ vmware_password }}"
        validate_certs: "{{ vmware_validate_certs | default(false) | bool }}"
  block:
    - name: "VM | Include dispatcher"
      ansible.builtin.include_role:
        name: internal.core.dispatch
      vars:
        _ncs_role_label: VM
        _ncs_task_root: "{{ role_path }}/tasks"
        _ncs_default_action: collect
        _ncs_action_routes:
          - collect
        _ncs_allowed_operations:
          - snapshot
        _ncs_extra_validations:
          - (_ncs_requested_operation == 'none') or (_ncs_requested_action == 'remediate')
        _dispatch_map:
          collect: collect
          snapshot: snapshot
          _default_: stig
