---
# internal.vmware.vcsa : tasks/stig_v1r4/vars/rhttpproxy.yaml
# Toggle flags (run_*) + variable bindings consumed by stig_v1r4/rhttpproxy.yaml.
# Loaded once per service from stig_service.yaml::include_vars.

# =============================================================================
# TOGGLE FLAGS
# =============================================================================

run_create_backups: true


# VCRP-70-000001
run_config_tcpkeepalivetimesec: true

# VCRP-70-000002
run_config_maxhttpsconnections: true

# VCRP-70-000003
run_config_fips: true

# VCRP-70-000004
run_config_tls: true

# VCRP-70-000005
run_key_permissions: true

# VCRP-70-000006
run_config_ssl: true

# VCRP-70-000007
run_syslog_config_rhttpproxy: true

# VCRP-70-000008
run_syslog_config_envoy: true

# =============================================================================
# VARIABLES
# =============================================================================

# rhttpproxy variables

# config.xml variables
var_config_xml_path: '/etc/vmware-rhttpproxy/config.xml'
var_config_xml_tcpkeepalivetimesec: '180'
var_config_xml_maxhttpsconnections: '2048'
var_config_xml_fips: 'true'
var_config_xml_tls: 'tls1.2'
var_config_xml_ssl_private_key: '/etc/vmware-rhttpproxy/ssl/rui.key'
var_config_xml_ssl_cert: '/etc/vmware-rhttpproxy/ssl/rui.crt'
var_config_xml_ssl_vecs: 'localhost'

# misc variables
var_key_path: '/etc/vmware-rhttpproxy/ssl/rui.key'
var_syslog_conf_path: '/etc/vmware-syslog/vmware-services-rhttpproxy.conf'
var_syslog_conf_path2: '/etc/vmware-syslog/vmware-services-envoy.conf'
