"""CKLB artifact generation for STIG results."""

import json
import re
from pathlib import Path
from typing import Any


def _strip_html(text: str) -> str:
    return re.sub(r"<[^>]+>", "", text)


def generate_cklb(
    hostname: str,
    audit_data: list[dict[str, Any]],
    skeleton_path: Path,
    output_path: Path,
    ip_address: str = "",
) -> None:
    """
    Generates a CKLB file from audit data and a skeleton.
    """
    if not skeleton_path.exists():
        raise FileNotFoundError(f"CKLB skeleton not found: {skeleton_path}")

    with open(skeleton_path) as f:
        skeleton = json.load(f)

    # Create map of results by rule ID (or version)
    # The skeleton usually uses 'rule_version' to match against the rule ID in our audit
    audit_map = {}
    for res in audit_data:
        rid = res.get("rule_id") or res.get("id")
        if rid:
            audit_map[str(rid).strip()] = res

    # Build the CKLB structure based on the skeleton
    cklb = {
        "title": skeleton.get("title"),
        "id": skeleton.get("id"),
        "cklb_version": skeleton.get("cklb_version"),
        "active": True,
        "mode": 1,
        "has_path": False,
        "target_data": {
            "target_type": "Computing",
            "host_name": hostname,
            "fqdn": hostname,
            "ip_address": ip_address,
            "role": "Workstation",
            "comments": "Generated by NCS Reporter",
        },
        "stigs": [],
    }

    for stig in skeleton.get("stigs", []):
        new_stig = {
            "stig_name": stig.get("stig_name"),
            "display_name": stig.get("display_name"),
            "stig_id": stig.get("stig_id"),
            "release_info": stig.get("release_info"),
            "version": stig.get("version"),
            "uuid": stig.get("uuid"),
            "size": stig.get("size"),
            "rules": [],
        }

        for rule in stig.get("rules", []):
            # Try to find a match in our audit data using several possible identifiers
            rule_version = str(rule.get("rule_version", "")).strip()
            rule_id = str(rule.get("rule_id", "")).strip()
            group_id = str(rule.get("group_id", "")).strip()

            audit_result = audit_map.get(rule_version) or audit_map.get(rule_id) or audit_map.get(group_id)

            status = "not_reviewed"
            details = ""
            comment = ""

            if audit_result:
                res_status = str(audit_result.get("status", "")).lower()
                rule_title = rule.get("rule_title") or rule_version
                check_content = _strip_html(rule.get("check_content") or "")
                fix_text_detail = _strip_html(rule.get("fix_text") or "")
                host_name = audit_result.get("name") or hostname

                if res_status in ["failed", "fail", "open"]:
                    status = "open"
                    details = (
                        f"Automated audit of {rule_version} on {host_name} identified a non-compliant setting.\n\n"
                        f"Check performed:\n{check_content}\n\n"
                        f"Recommended fix:\n{fix_text_detail}"
                    ) if check_content else f"Automated audit of {rule_version} on {host_name} identified a non-compliant setting."
                    comment = f"OPEN: {rule_title} — automated check found non-compliant configuration on {host_name}."
                elif res_status in ["passed", "pass", "not_a_finding", "notafinding"]:
                    status = "not_a_finding"
                    details = (
                        f"Automated audit of {rule_version} on {host_name} verified compliant configuration.\n\n"
                        f"Check performed:\n{check_content}"
                    ) if check_content else f"Automated audit of {rule_version} on {host_name} verified compliant configuration."
                    comment = f"NOT A FINDING: {rule_title} — verified compliant on {host_name} via automated audit."
                elif res_status == "fixed":
                    status = "not_a_finding"
                    details = (
                        f"Automated remediation of {rule_version} on {host_name} corrected the setting.\n\n"
                        f"Fix applied:\n{fix_text_detail}"
                    ) if fix_text_detail else f"Automated remediation of {rule_version} on {host_name} corrected the setting."
                    comment = f"NOT A FINDING (REMEDIATED): {rule_title} — setting corrected on {host_name} via automated remediation."
                elif res_status in ["na", "not_applicable", "notapplicable"]:
                    status = "not_applicable"
                    details = f"Automated audit determined {rule_version} is not applicable to {host_name}."
                    comment = f"NOT APPLICABLE: {rule_title} — rule does not apply to {host_name}."

            new_rule = {
                "rule_id": rule.get("rule_id"),
                "rule_version": rule.get("rule_version"),
                "group_id": rule.get("group_id"),
                "status": status,
                "finding_details": details,
                "comments": comment,
                "severity": rule.get("severity"),
                "group_title": rule.get("group_title"),
                "rule_title": rule.get("rule_title"),
                "fix_text": rule.get("fix_text"),
                "check_content": rule.get("check_content"),
                "discussion": rule.get("discussion"),
                "cci_ref": (rule.get("ccis") or [""])[0],
            }
            rules_list = new_stig.get("rules")
            if isinstance(rules_list, list):
                rules_list.append(new_rule)

        stigs_list = cklb.get("stigs")
        if isinstance(stigs_list, list):
            stigs_list.append(new_stig)

    with open(output_path, "w") as f:
        json.dump(cklb, f, indent=2)
