---
galaxy_info:
  author: NCS
  description: VMware VCSA STIG audit and remediation orchestration
  company: NCS
  license: GPL-3.0-or-later
  min_ansible_version: "2.15"
  platforms:
    - name: GenericUNIX
      versions:
        - all
  galaxy_tags:
        - vmware
        - vcsa
        - vcenter
        - stig
        - audit

dependencies:
  - role: internal.vmware.common
