---
# internal.linux.ubuntu : tasks/main.yaml

- name: "Ubuntu | Capture task root"
  ansible.builtin.set_fact:
    _ncs_task_root: "{{ role_path }}/tasks"
  changed_when: false

- name: "Ubuntu | Dispatch"
  ansible.builtin.include_role:
    name: internal.core.dispatch
  vars:
    _ncs_role_label: Ubuntu
    _ncs_default_action: collect
    _ncs_allowed_operations:
      - maintain
      - patch
      - password_status
      - password_rotate
    _ncs_extra_validations:
      - "{{ (_ncs_requested_operation not in ['patch', 'maintain', 'password_rotate']) or (_ncs_requested_action == 'remediate') }}"
      - "{{ (_ncs_requested_operation != 'password_status') or (_ncs_requested_action in ['audit', 'verify']) }}"
    _dispatch_map:
      stig: stig
      maintain: maintain/package_upgrade
      patch: maintain/package_update
      password_status: maintain/password_status
      password_rotate: maintain/password_rotate
      _default_: collect
