#!/usr/bin/env python3
"""Regenerate playbooks/site_<verb>_only.yml from installed internal.* collections.

Rather than hard-pinning vmware + linux + windows + ... at the top of every
site playbook, this script enumerates
``collections/ansible_collections/internal/*/playbooks/<verb>.yml`` and emits a
static orchestrator that imports each one it finds. A collection that ships a
canonical verb entry point gets picked up automatically; one that doesn't
(e.g. internal.core) is skipped.

Run via ``just regenerate-site-playbooks`` or as part of ``install-collections``.
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
INTERNAL_ROOT = REPO_ROOT / "collections" / "ansible_collections" / "internal"
SITE_DIR = REPO_ROOT / "playbooks"

# Map from site file name → collection-level verb playbook name. Add new verbs
# here as they're introduced; the script no-ops when no collection implements
# a given verb.
VERBS = {
    "site_collect_only.yml":    "collect.yml",
    "site_stig_audit.yml":      "stig_audit.yml",
    "site_remediate.yml":       "stig_remediate.yml",
}

HEADER = """\
---
# playbooks/{site_file}
# Auto-generated by scripts/regenerate_site_playbooks.py — do not edit by
# hand. Rebuilt whenever `just regenerate-site-playbooks` or
# `just install-collections` runs.

- name: "Phase 1: Initialize Reporting Environment"
  ansible.builtin.import_playbook: core/setup_env.yml

"""

REPORT_FOOTER = """
- name: "Phase 4: Unified Infrastructure Reporting"
  ansible.builtin.import_playbook: core/generate_reports.yml
"""


def discover_collections() -> list[str]:
    if not INTERNAL_ROOT.is_dir():
        return []
    return sorted(p.name for p in INTERNAL_ROOT.iterdir() if p.is_dir())


def emit(site_file: str, verb_file: str, include_reports: bool) -> bool:
    """Write playbooks/<site_file>; return True if content changed."""
    imports: list[str] = []
    for col in discover_collections():
        pb = INTERNAL_ROOT / col / "playbooks" / verb_file
        if pb.is_file():
            fqcn = f"internal.{col}.{verb_file.removesuffix('.yml')}"
            imports.append(
                f'- name: "Phase 2 | {col} {verb_file.removesuffix(".yml")}"\n'
                f'  ansible.builtin.import_playbook: {fqcn}\n'
            )

    body = HEADER.format(site_file=site_file) + "\n".join(imports)
    if include_reports:
        body += REPORT_FOOTER

    dest = SITE_DIR / site_file
    prev = dest.read_text() if dest.is_file() else None
    if prev == body:
        return False
    dest.write_text(body)
    return True


def main() -> int:
    if not INTERNAL_ROOT.is_dir():
        print(f"internal collections not installed at {INTERNAL_ROOT}; skipping", file=sys.stderr)
        return 0

    collections = discover_collections()
    print(f"Discovered {len(collections)} installed internal collection(s): {', '.join(collections)}")

    changed = False
    for site_file, verb_file in VERBS.items():
        include_reports = site_file in ("site_collect_only.yml", "site_stig_audit.yml")
        if emit(site_file, verb_file, include_reports):
            changed = True
            print(f"  ✓ regenerated playbooks/{site_file}")
        else:
            print(f"    (unchanged) playbooks/{site_file}")

    if not changed:
        print("Site playbooks already up to date.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
