# yaml-language-server: $schema=../../.schemas/report_schema.json
config:
  platform: linux/ubuntu
  stig:
    ansible_playbook:
      path: "playbooks/ubuntu_stig_remediate.yml"
      target_var: "ubuntu_target_hosts"
    rule_prefix_to_platform:
      UBTU: ubuntu
      GEN: ubuntu
  extra_fleet_widget_columns:
    'Distribution': "{{ distribution }}"
    'Uptime (d)': "{{ uptime_days }}"
    'Critical': "{{ _critical_count }}"
    'Warning': "{{ _warning_count }}"

vars:
  $include: "linux_base_fields.yaml"

alerts:
  $include: "linux_base_alerts.yaml"

widgets:
  $include: "linux_base_widgets.yaml"
